services:
  postgresql:
    image: postgres:16
    container_name: carrental_postgresql
    restart: unless-stopped
    environment:
      POSTGRES_DB: carrental_docker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fahmi123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d carrental_docker"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend-express
      dockerfile: Docker/Dockerfile.nginx.local
    container_name: carrental-backend
    ports:
      - "3000:80"
    restart: unless-stopped
    env_file:
      - ./backend-express/.env
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://postgres:fahmi123@postgresql:5432/carrental_docker?schema=public
    depends_on:
      postgresql:
        condition: service_healthy
    volumes:
      - ./backend-express:/app
      - backend_node_modules:/app/node_modules

  frontend:
    build:
      context: ./frontend-react
      dockerfile: Docker/Dockerfile.nginx.local
      args:
        VITE_API_BE_URL: http://localhost:3000
    container_name: carrental-frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  backend_node_modules:
  postgres_data:
