FROM node:18.20.4-bookworm-slim

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
        g++ \
        libcurl4 \
        make \
        nginx \
        openssl \
        procps \
        python3 \
        supervisor \
    && rm -rf /var/lib/apt/lists/* /etc/nginx/sites-enabled/default \
    && npm install -g pm2

RUN mkdir -p /etc/nginx/templates

COPY Docker/Config/nginx/default.conf /etc/nginx/templates/default.conf.template
COPY Docker/Services/supervisord.nginx.conf /etc/supervisor/conf.d/supervisord.conf
COPY Docker/Services/start-container.sh /usr/local/bin/start-container

# copy dari leptop ke /app container
COPY package*.json ./
COPY prisma ./prisma/

RUN npm ci \
    && npx prisma generate \
    && chmod +x /usr/local/bin/start-container

# copy semua project ke /app container
COPY . .

EXPOSE 80

CMD ["start-container"]
